trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: lint
    jobs:
      - job: shellcheck
        steps:
          - bash: sudo apt-get install shellcheck
            displayName: 'Install shellcheck'
          - bash: shellcheck dump
            displayName: 'Running shellcheck'
