#!/usr/bin/env bash

set -e
set -f

DUMP_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/dump"

[[ ! -d "${DUMP_DIR}" ]] && mkdir -p "${DUMP_DIR}"


function put() {
  local files_to_remove="$@" esc=$(printf '\033') candidates=()
  if [[ -z "${files_to_remove}" ]]; then
    while IFS= read -r line; do
      candidates+=("${esc}[34m${line}/${esc}[m")
    done < <(fd --type d -d 1)
    while IFS= read -r line; do
      candidates+=("${line}")
    done < <(fd --type f -d 1)

    files_to_remove=$(
      IFS=$'\n'
      echo "${candidates[*]}" \
        | fzf --ansi --exit-0 --multi
    )
  fi
  [[ -z "${files_to_remove}" ]] && exit 1
  while IFS=$'\n' read -r line; do
    mv "${line}" "${DUMP_DIR}"/
    touch "${DUMP_DIR}"/"${line}"
    echo "dump: ${line}"
  done < <(echo "${files_to_remove}" | tr " " "\n")
}

function regret() {
  local action_mode="first" files_to_reset esc=$(printf '\033') candidates=()
  case "$1" in
    -s|--select)
      action_mode="select"
      shift
      ;;
    *)
      [[ -n "$1" ]] && \
        echo "Invalid option $1" 1>&2 && \
        exit 1
  esac
}

action_comand="put"
case $1 in
  put)
    action_comand="put"
    shift
    ;;
  clean)
    action_comand="clean"
    shift
    ;;
  regret)
    action_comand='regret'
    shift
    ;;
esac

eval "${action_comand}" "$*"
